on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]
    issue_comment:
        types: [created]

jobs:
    review:
        permissions:
            contents: read
            pull-requests: write
            checks: write
        uses: DataDog/code-review-action/.github/workflows/code-review.yml@feat/ai-code-review-action
        with:
            provider: gemini
            trigger_mode: on_demand
            review_event: ALL
            prompt_file: prompt.md
        secrets:
            openai_api_key: ${{ secrets.OPENAI_API_KEY }}
            anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
            gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
